// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booster_configs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateBoosterConfigs = `-- name: DeactivateBoosterConfigs :exec
UPDATE booster_configs SET is_active = false
WHERE set_code = $1 AND booster_type = $2 AND is_active
`

type DeactivateBoosterConfigsParams struct {
	SetCode     string `json:"set_code"`
	BoosterType string `json:"booster_type"`
}

func (q *Queries) DeactivateBoosterConfigs(ctx context.Context, arg DeactivateBoosterConfigsParams) error {
	_, err := q.db.Exec(ctx, deactivateBoosterConfigs, arg.SetCode, arg.BoosterType)
	return err
}

const getActiveBoosterConfig = `-- name: GetActiveBoosterConfig :one
SELECT id, set_code, booster_type, version, config, is_active, created_at FROM booster_configs
WHERE set_code = $1 AND booster_type = $2 AND is_active
`

type GetActiveBoosterConfigParams struct {
	SetCode     string `json:"set_code"`
	BoosterType string `json:"booster_type"`
}

func (q *Queries) GetActiveBoosterConfig(ctx context.Context, arg GetActiveBoosterConfigParams) (BoosterConfig, error) {
	row := q.db.QueryRow(ctx, getActiveBoosterConfig, arg.SetCode, arg.BoosterType)
	var i BoosterConfig
	err := row.Scan(
		&i.ID,
		&i.SetCode,
		&i.BoosterType,
		&i.Version,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertBoosterConfig = `-- name: InsertBoosterConfig :one
INSERT INTO booster_configs (set_code, booster_type, version, config, is_active)
VALUES ($1, $2, $3, $4, true)
RETURNING id, set_code, booster_type, version, config, is_active, created_at
`

type InsertBoosterConfigParams struct {
	SetCode     string `json:"set_code"`
	BoosterType string `json:"booster_type"`
	Version     int32  `json:"version"`
	Config      []byte `json:"config"`
}

func (q *Queries) InsertBoosterConfig(ctx context.Context, arg InsertBoosterConfigParams) (BoosterConfig, error) {
	row := q.db.QueryRow(ctx, insertBoosterConfig,
		arg.SetCode,
		arg.BoosterType,
		arg.Version,
		arg.Config,
	)
	var i BoosterConfig
	err := row.Scan(
		&i.ID,
		&i.SetCode,
		&i.BoosterType,
		&i.Version,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveBoosterConfigsWithSetName = `-- name: ListActiveBoosterConfigsWithSetName :many
SELECT bc.set_code, s.name AS set_name, COALESCE(md5(s.pack_image), '')::text AS pack_image_hash, bc.booster_type,
       s.pack_price_eur, s.pack_priced_at
FROM booster_configs bc
JOIN sets s ON s.code = bc.set_code
WHERE bc.is_active
ORDER BY bc.set_code, bc.booster_type
`

type ListActiveBoosterConfigsWithSetNameRow struct {
	SetCode       string             `json:"set_code"`
	SetName       string             `json:"set_name"`
	PackImageHash string             `json:"pack_image_hash"`
	BoosterType   string             `json:"booster_type"`
	PackPriceEur  pgtype.Float8      `json:"pack_price_eur"`
	PackPricedAt  pgtype.Timestamptz `json:"pack_priced_at"`
}

// md5(NULL) is NULL, and sqlc types this column as non-nullable text, so
// COALESCE to "" (treated as "no pack image" in Go) rather than let a set
// with no image fail to scan.
func (q *Queries) ListActiveBoosterConfigsWithSetName(ctx context.Context) ([]ListActiveBoosterConfigsWithSetNameRow, error) {
	rows, err := q.db.Query(ctx, listActiveBoosterConfigsWithSetName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveBoosterConfigsWithSetNameRow
	for rows.Next() {
		var i ListActiveBoosterConfigsWithSetNameRow
		if err := rows.Scan(
			&i.SetCode,
			&i.SetName,
			&i.PackImageHash,
			&i.BoosterType,
			&i.PackPriceEur,
			&i.PackPricedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBoosterConfigVersion = `-- name: NextBoosterConfigVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM booster_configs
WHERE set_code = $1 AND booster_type = $2
`

type NextBoosterConfigVersionParams struct {
	SetCode     string `json:"set_code"`
	BoosterType string `json:"booster_type"`
}

func (q *Queries) NextBoosterConfigVersion(ctx context.Context, arg NextBoosterConfigVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextBoosterConfigVersion, arg.SetCode, arg.BoosterType)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}
