// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booster_configs.sql

package db

import (
	"context"
)

const deactivateBoosterConfigs = `-- name: DeactivateBoosterConfigs :exec
UPDATE booster_configs SET is_active = false
WHERE set_code = $1 AND booster_type = $2 AND is_active
`

type DeactivateBoosterConfigsParams struct {
	SetCode     string `json:"set_code"`
	BoosterType string `json:"booster_type"`
}

func (q *Queries) DeactivateBoosterConfigs(ctx context.Context, arg DeactivateBoosterConfigsParams) error {
	_, err := q.db.Exec(ctx, deactivateBoosterConfigs, arg.SetCode, arg.BoosterType)
	return err
}

const insertBoosterConfig = `-- name: InsertBoosterConfig :one
INSERT INTO booster_configs (set_code, booster_type, version, config, is_active)
VALUES ($1, $2, $3, $4, true)
RETURNING id, set_code, booster_type, version, config, is_active, created_at
`

type InsertBoosterConfigParams struct {
	SetCode     string `json:"set_code"`
	BoosterType string `json:"booster_type"`
	Version     int32  `json:"version"`
	Config      []byte `json:"config"`
}

func (q *Queries) InsertBoosterConfig(ctx context.Context, arg InsertBoosterConfigParams) (BoosterConfig, error) {
	row := q.db.QueryRow(ctx, insertBoosterConfig,
		arg.SetCode,
		arg.BoosterType,
		arg.Version,
		arg.Config,
	)
	var i BoosterConfig
	err := row.Scan(
		&i.ID,
		&i.SetCode,
		&i.BoosterType,
		&i.Version,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const nextBoosterConfigVersion = `-- name: NextBoosterConfigVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM booster_configs
WHERE set_code = $1 AND booster_type = $2
`

type NextBoosterConfigVersionParams struct {
	SetCode     string `json:"set_code"`
	BoosterType string `json:"booster_type"`
}

func (q *Queries) NextBoosterConfigVersion(ctx context.Context, arg NextBoosterConfigVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextBoosterConfigVersion, arg.SetCode, arg.BoosterType)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}
