// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertCard = `-- name: UpsertCard :one
INSERT INTO cards (id, set_code, name, rarity, collector_number, scryfall_id, image_uris, finishes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    name             = EXCLUDED.name,
    rarity           = EXCLUDED.rarity,
    collector_number = EXCLUDED.collector_number,
    scryfall_id      = EXCLUDED.scryfall_id,
    image_uris       = EXCLUDED.image_uris,
    finishes         = EXCLUDED.finishes
RETURNING id, set_code, name, rarity, collector_number, scryfall_id, image_uris, finishes, created_at
`

type UpsertCardParams struct {
	ID              pgtype.UUID `json:"id"`
	SetCode         string      `json:"set_code"`
	Name            string      `json:"name"`
	Rarity          string      `json:"rarity"`
	CollectorNumber string      `json:"collector_number"`
	ScryfallID      pgtype.UUID `json:"scryfall_id"`
	ImageUris       []byte      `json:"image_uris"`
	Finishes        []string    `json:"finishes"`
}

func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, upsertCard,
		arg.ID,
		arg.SetCode,
		arg.Name,
		arg.Rarity,
		arg.CollectorNumber,
		arg.ScryfallID,
		arg.ImageUris,
		arg.Finishes,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.SetCode,
		&i.Name,
		&i.Rarity,
		&i.CollectorNumber,
		&i.ScryfallID,
		&i.ImageUris,
		&i.Finishes,
		&i.CreatedAt,
	)
	return i, err
}
