// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCardsWithMcmID = `-- name: ListCardsWithMcmID :many
SELECT id, mcm_id FROM cards WHERE mcm_id IS NOT NULL
`

type ListCardsWithMcmIDRow struct {
	ID    pgtype.UUID `json:"id"`
	McmID pgtype.Int4 `json:"mcm_id"`
}

func (q *Queries) ListCardsWithMcmID(ctx context.Context) ([]ListCardsWithMcmIDRow, error) {
	rows, err := q.db.Query(ctx, listCardsWithMcmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsWithMcmIDRow
	for rows.Next() {
		var i ListCardsWithMcmIDRow
		if err := rows.Scan(&i.ID, &i.McmID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardPrices = `-- name: UpdateCardPrices :exec
UPDATE cards c SET price_eur = NULLIF(u.price, 0), price_foil_eur = NULLIF(u.price_foil, 0), priced_at = $1
FROM (SELECT unnest($2::uuid[]) AS id, unnest($3::float8[]) AS price, unnest($4::float8[]) AS price_foil) u
WHERE c.id = u.id
`

type UpdateCardPricesParams struct {
	PricedAt   pgtype.Timestamptz `json:"priced_at"`
	Ids        []pgtype.UUID      `json:"ids"`
	Prices     []float64          `json:"prices"`
	FoilPrices []float64          `json:"foil_prices"`
}

// One statement for every card instead of a round-trip each. A 0 price
// means "no figure" and is stored as NULL (float8[] params can't carry
// NULLs through sqlc).
func (q *Queries) UpdateCardPrices(ctx context.Context, arg UpdateCardPricesParams) error {
	_, err := q.db.Exec(ctx, updateCardPrices,
		arg.PricedAt,
		arg.Ids,
		arg.Prices,
		arg.FoilPrices,
	)
	return err
}

const upsertCard = `-- name: UpsertCard :one
INSERT INTO cards (id, set_code, name, rarity, collector_number, scryfall_id, image_uris, finishes, mcm_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    name             = EXCLUDED.name,
    rarity           = EXCLUDED.rarity,
    collector_number = EXCLUDED.collector_number,
    scryfall_id      = EXCLUDED.scryfall_id,
    image_uris       = EXCLUDED.image_uris,
    finishes         = EXCLUDED.finishes,
    mcm_id           = EXCLUDED.mcm_id
RETURNING id, set_code, name, rarity, collector_number, scryfall_id, image_uris, finishes, created_at, mcm_id, price_eur, price_foil_eur, priced_at
`

type UpsertCardParams struct {
	ID              pgtype.UUID `json:"id"`
	SetCode         string      `json:"set_code"`
	Name            string      `json:"name"`
	Rarity          string      `json:"rarity"`
	CollectorNumber string      `json:"collector_number"`
	ScryfallID      pgtype.UUID `json:"scryfall_id"`
	ImageUris       []byte      `json:"image_uris"`
	Finishes        []string    `json:"finishes"`
	McmID           pgtype.Int4 `json:"mcm_id"`
}

// Price columns are deliberately not touched here: re-importing a set
// refreshes card data, not prices (cmd/prices owns those).
func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, upsertCard,
		arg.ID,
		arg.SetCode,
		arg.Name,
		arg.Rarity,
		arg.CollectorNumber,
		arg.ScryfallID,
		arg.ImageUris,
		arg.Finishes,
		arg.McmID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.SetCode,
		&i.Name,
		&i.Rarity,
		&i.CollectorNumber,
		&i.ScryfallID,
		&i.ImageUris,
		&i.Finishes,
		&i.CreatedAt,
		&i.McmID,
		&i.PriceEur,
		&i.PriceFoilEur,
		&i.PricedAt,
	)
	return i, err
}
