// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertPackOpenCards implements pgx.CopyFromSource.
type iteratorForInsertPackOpenCards struct {
	rows                 []InsertPackOpenCardsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertPackOpenCards) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertPackOpenCards) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PackOpenID,
		r.rows[0].Slot,
		r.rows[0].SheetName,
		r.rows[0].Foil,
		r.rows[0].CardID,
	}, nil
}

func (r iteratorForInsertPackOpenCards) Err() error {
	return nil
}

func (q *Queries) InsertPackOpenCards(ctx context.Context, arg []InsertPackOpenCardsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"pack_open_cards"}, []string{"pack_open_id", "slot", "sheet_name", "foil", "card_id"}, &iteratorForInsertPackOpenCards{rows: arg})
}
