// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BoosterConfig struct {
	ID          int64              `json:"id"`
	SetCode     string             `json:"set_code"`
	BoosterType string             `json:"booster_type"`
	Version     int32              `json:"version"`
	Config      []byte             `json:"config"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Card struct {
	ID              pgtype.UUID        `json:"id"`
	SetCode         string             `json:"set_code"`
	Name            string             `json:"name"`
	Rarity          string             `json:"rarity"`
	CollectorNumber string             `json:"collector_number"`
	ScryfallID      pgtype.UUID        `json:"scryfall_id"`
	ImageUris       []byte             `json:"image_uris"`
	Finishes        []string           `json:"finishes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	McmID           pgtype.Int4        `json:"mcm_id"`
	PriceEur        pgtype.Float8      `json:"price_eur"`
	PriceFoilEur    pgtype.Float8      `json:"price_foil_eur"`
	PricedAt        pgtype.Timestamptz `json:"priced_at"`
}

type PackOpen struct {
	ID               pgtype.UUID        `json:"id"`
	BoosterConfigID  int64              `json:"booster_config_id"`
	PackVariantIndex int32              `json:"pack_variant_index"`
	Seed             []byte             `json:"seed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PackOpenCard struct {
	PackOpenID pgtype.UUID `json:"pack_open_id"`
	Slot       int32       `json:"slot"`
	SheetName  string      `json:"sheet_name"`
	Foil       bool        `json:"foil"`
	CardID     pgtype.UUID `json:"card_id"`
}

type Set struct {
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PackImage    []byte             `json:"pack_image"`
	McmID        pgtype.Int4        `json:"mcm_id"`
	PackPriceEur pgtype.Float8      `json:"pack_price_eur"`
	PackPricedAt pgtype.Timestamptz `json:"pack_priced_at"`
	ReleaseDate  pgtype.Date        `json:"release_date"`
}
