// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pack_opens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPackOpen = `-- name: GetPackOpen :one
SELECT po.id, po.created_at, bc.set_code, bc.booster_type, bc.version AS config_version
FROM pack_opens po
JOIN booster_configs bc ON bc.id = po.booster_config_id
WHERE po.id = $1
`

type GetPackOpenRow struct {
	ID            pgtype.UUID        `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SetCode       string             `json:"set_code"`
	BoosterType   string             `json:"booster_type"`
	ConfigVersion int32              `json:"config_version"`
}

func (q *Queries) GetPackOpen(ctx context.Context, id pgtype.UUID) (GetPackOpenRow, error) {
	row := q.db.QueryRow(ctx, getPackOpen, id)
	var i GetPackOpenRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SetCode,
		&i.BoosterType,
		&i.ConfigVersion,
	)
	return i, err
}

const insertPackOpen = `-- name: InsertPackOpen :one
INSERT INTO pack_opens (booster_config_id, pack_variant_index, seed)
VALUES ($1, $2, $3)
RETURNING id, booster_config_id, pack_variant_index, seed, created_at
`

type InsertPackOpenParams struct {
	BoosterConfigID  int64  `json:"booster_config_id"`
	PackVariantIndex int32  `json:"pack_variant_index"`
	Seed             []byte `json:"seed"`
}

func (q *Queries) InsertPackOpen(ctx context.Context, arg InsertPackOpenParams) (PackOpen, error) {
	row := q.db.QueryRow(ctx, insertPackOpen, arg.BoosterConfigID, arg.PackVariantIndex, arg.Seed)
	var i PackOpen
	err := row.Scan(
		&i.ID,
		&i.BoosterConfigID,
		&i.PackVariantIndex,
		&i.Seed,
		&i.CreatedAt,
	)
	return i, err
}

const insertPackOpenCard = `-- name: InsertPackOpenCard :exec
INSERT INTO pack_open_cards (pack_open_id, slot, sheet_name, foil, card_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPackOpenCardParams struct {
	PackOpenID pgtype.UUID `json:"pack_open_id"`
	Slot       int32       `json:"slot"`
	SheetName  string      `json:"sheet_name"`
	Foil       bool        `json:"foil"`
	CardID     pgtype.UUID `json:"card_id"`
}

func (q *Queries) InsertPackOpenCard(ctx context.Context, arg InsertPackOpenCardParams) error {
	_, err := q.db.Exec(ctx, insertPackOpenCard,
		arg.PackOpenID,
		arg.Slot,
		arg.SheetName,
		arg.Foil,
		arg.CardID,
	)
	return err
}

const listPackOpenCards = `-- name: ListPackOpenCards :many
SELECT poc.slot, poc.sheet_name, poc.foil,
       c.id AS card_id, c.name, c.rarity, c.collector_number, c.set_code, c.image_uris
FROM pack_open_cards poc
JOIN cards c ON c.id = poc.card_id
WHERE poc.pack_open_id = $1
ORDER BY poc.slot
`

type ListPackOpenCardsRow struct {
	Slot            int32       `json:"slot"`
	SheetName       string      `json:"sheet_name"`
	Foil            bool        `json:"foil"`
	CardID          pgtype.UUID `json:"card_id"`
	Name            string      `json:"name"`
	Rarity          string      `json:"rarity"`
	CollectorNumber string      `json:"collector_number"`
	SetCode         string      `json:"set_code"`
	ImageUris       []byte      `json:"image_uris"`
}

func (q *Queries) ListPackOpenCards(ctx context.Context, packOpenID pgtype.UUID) ([]ListPackOpenCardsRow, error) {
	rows, err := q.db.Query(ctx, listPackOpenCards, packOpenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackOpenCardsRow
	for rows.Next() {
		var i ListPackOpenCardsRow
		if err := rows.Scan(
			&i.Slot,
			&i.SheetName,
			&i.Foil,
			&i.CardID,
			&i.Name,
			&i.Rarity,
			&i.CollectorNumber,
			&i.SetCode,
			&i.ImageUris,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
