// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sets.sql

package db

import (
	"context"
)

const upsertSet = `-- name: UpsertSet :one
INSERT INTO sets (code, name)
VALUES ($1, $2)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name
RETURNING code, name, created_at
`

type UpsertSetParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) UpsertSet(ctx context.Context, arg UpsertSetParams) (Set, error) {
	row := q.db.QueryRow(ctx, upsertSet, arg.Code, arg.Name)
	var i Set
	err := row.Scan(&i.Code, &i.Name, &i.CreatedAt)
	return i, err
}
